### ISSUE TITLE
Tela dos jogadores + estrelas

### ISSUE THREAD

**Issue by PedroFAC** [PedroFAC/app-racha#1]

**Comment by eduardoabreu09** [comment]
![b54b8949-cea2-42e6-a36e-af62dff39616](https://github.com/user-attachments/assets/ec2b56d3-486b-4b7a-873b-fd64c69522a9)

**Comment by eduardoabreu09** [comment]
- [x] Função de criar jogadores
- [ ] Listar jogadores
- [ ] Editar
- [ ] Remover jogadores
